"""Brief 报告的自包含 HTML 生成与并行编排。"""

import asyncio
import html
import json
import logging
import re
import time
from dataclasses import dataclass
from html.parser import HTMLParser

from openjiuwen_deepsearch.algorithm.brief_report.html_charts import (
    _TEMPLATE_BLOCK_RE,
    _extract_fragment_charts,
    _normalize_chart_configs,
    _validate_chart_configs,
    inject_chart_scripts,
    inject_echarts_library,
)
from openjiuwen_deepsearch.algorithm.brief_report.html_content import (
    BriefHtmlPreprocessResult,
    BriefHtmlSectionChunk,
    _render_references_html,
    _split_report_markdown,
    convert_inline_citations,
    preprocess_markdown,
)
from openjiuwen_deepsearch.algorithm.brief_report.html_safety import (
    _HTML_VOID_TAGS,
    _HtmlStructureScanner,
    _JAVASCRIPT_URL_RE,
    _SCRIPT_TAG_RE,
    _contains_event_attribute,
    _insert_before,
    _validate_css_references,
    final_security_assert,
    sanitize_html,
)
from openjiuwen_deepsearch.algorithm.prompts.template import apply_system_prompt
from openjiuwen_deepsearch.common.common_constants import ENGLISH
from openjiuwen_deepsearch.config.config import Config
from openjiuwen_deepsearch.utils.common_utils.llm_utils import ainvoke_llm_with_stats
from openjiuwen_deepsearch.utils.constants_utils.node_constants import AgentLlmName


logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class _ShellGenerationContext:
    """shell 生成所需的报告上下文。

    Attributes:
        title: 报告标题。
        summary_md: 核心摘要的 Markdown 内容。
        sections: 按报告顺序排列的章节块。
        language: 报告语言标识。
        errors: 上一轮生成或校验产生的错误信息。
    """

    title: str
    summary_md: str
    sections: list[BriefHtmlSectionChunk]
    language: str
    errors: list[str]


def validate_html_report(html_text: str) -> tuple[list[str], list[str]]:
    """对清理后的 HTML 聚合安全与图表结构校验。

    Args:
        html_text: 待校验的完整 HTML 文本。

    Returns:
        二元组，分别包含阻断生成的错误列表和不阻断生成的警告列表。
    """
    errors: list[str] = []
    warnings: list[str] = []
    lowered = html_text.lower()
    if "<!doctype html" not in lowered:
        errors.append("missing_doctype")
    for tag in ("html", "head", "body"):
        if f"<{tag}" not in lowered or f"</{tag}>" not in lowered:
            errors.append(f"missing_or_unclosed_{tag}")
    if _SCRIPT_TAG_RE.search(html_text):
        errors.append("script_tag_present")
    if _JAVASCRIPT_URL_RE.search(html_text):
        errors.append("javascript_url_present")

    scanner = _HtmlStructureScanner()
    scanner.feed(html_text)
    scanner.close()
    if _contains_event_attribute(html_text):
        errors.append("event_attribute_present")
    errors.extend(_validate_css_references(scanner))
    chart_errors, chart_warnings = _validate_chart_configs(scanner)
    errors.extend(chart_errors)
    warnings.extend(chart_warnings)
    return errors, warnings


def inject_ai_notice(html_text: str, language: str) -> str:
    """在 body 末尾确定性插入随语言切换的 AI 生成声明。

    Args:
        html_text: 已完成拼装的 HTML 文本。
        language: 报告语言标识；等于 ``ENGLISH`` 时使用英文声明。

    Returns:
        插入声明后的 HTML 文本。
    """
    text = (
        "This research report was generated by AI and is for reference only."
        if language == ENGLISH
        else "本研究报告由 AI 生成，仅供参考"
    )
    notice = (
        '<footer style="margin-top:48px;padding:26px 16px 10px;'
        'border-top:1px solid var(--border,#e8e6e0);text-align:center;">'
        '<p style="margin:0;font-size:12px;line-height:1.7;'
        'color:var(--text-muted,#8f8f8b);letter-spacing:.3px;">'
        '<span style="display:inline-block;padding:2px 10px;margin-right:8px;'
        'border-radius:999px;background:var(--accent-light,#f0efec);'
        'color:var(--accent,#6b6b68);font-weight:600;font-size:11px;'
        'line-height:1.5;">AI</span>'
        f"{text}</p></footer>"
    )
    return _insert_before(html_text, "</body>", f"{notice}\n")


_HTML_REPORT_BLOCK_RE = re.compile(r"(?s)<html_report>\s*(.*?)\s*</html_report>")
_HTML_SECTION_BLOCK_RE = re.compile(r"(?s)<html_section>\s*(.*?)\s*</html_section>")
_MOUNT_SECTIONS_RE = re.compile(r'(?is)<div id="brief-sections"[^>]*>\s*</div>')
_MOUNT_REFERENCES_RE = re.compile(r'(?is)<div id="brief-references"[^>]*>\s*</div>')
_SECTION_ROOT_RE = re.compile(r"(?is)<section\b[^>]*>")


def _extract_html_body(raw: str) -> str | None:
    """从 LLM 输出提取完整 HTML，兼容缺少外层包装或 html 闭合标签。

    Args:
        raw: LLM 返回的原始文本。

    Returns:
        可继续清理的 HTML 文本；无法识别完整文档时返回 ``None``。
    """
    match = _HTML_REPORT_BLOCK_RE.search(raw)
    if match is not None:
        return match.group(1)
    lowered = raw.lower()
    start = lowered.find("<!doctype")
    if start < 0:
        return None
    end = lowered.rfind("</html>")
    if end >= 0:
        return raw[start:end + len("</html>")].strip()
    if "</body>" in lowered:
        return raw[start:].rstrip().removesuffix("</html_report>").rstrip() + "\n</html>"
    return None


def _extract_section_fragment(raw: str) -> str | None:
    """从 LLM 输出提取章节片段，兼容裸 h2 片段。

    Args:
        raw: LLM 返回的原始文本。

    Returns:
        去除外层协议标记后的章节 HTML；无法识别章节时返回 ``None``。
    """
    match = _HTML_SECTION_BLOCK_RE.search(raw)
    if match is not None:
        return match.group(1)
    stripped = re.sub(r"(?m)^\s*```[a-zA-Z]*\s*$", "", raw).strip()
    if "<h2" in stripped.lower():
        return stripped
    return None


def _sanitize_fragment(fragment: str) -> str:
    """包成完整文档复用 sanitizer，再取回 body 内容。

    Args:
        fragment: 单个章节的 HTML 片段。

    Returns:
        清理后的章节 HTML；包装或清理结果缺少 body 边界时返回空字符串。
    """
    wrapped = f"<!DOCTYPE html><html><head></head><body>{fragment}</body></html>"
    cleaned = sanitize_html(wrapped)
    start = cleaned.find("<body>")
    end = cleaned.rfind("</body>")
    if start < 0 or end < 0:
        return ""
    return cleaned[start + len("<body>"):end]


def _ensure_section_anchor(fragment: str, section_id: str) -> str:
    """为章节根元素确定性补充 TOC 锚点。

    Args:
        fragment: 清理后的章节 HTML 片段。
        section_id: 章节唯一标识。

    Returns:
        根 ``section`` 标签带有 ``section-{section_id}`` 锚点的 HTML 片段。
    """
    match = _SECTION_ROOT_RE.search(fragment)
    if match is None:
        return fragment
    anchor = html.escape(f"section-{section_id}", quote=True)
    tag = match.group(0)
    if re.search(r"\bid\s*=", tag, re.IGNORECASE):
        tag = re.sub(
            r"(\bid\s*=\s*)(?:\"[^\"]*\"|'[^']*'|[^\s>]+)",
            rf'\1"{anchor}"',
            tag,
            count=1,
            flags=re.IGNORECASE,
        )
    else:
        tag = tag[:-1] + f' id="{anchor}">'
    return fragment[:match.start()] + tag + fragment[match.end():]


def _error_feedback_lines(errors: list[str]) -> list[str]:
    """把上一轮错误格式化为可执行的 LLM 反馈。

    Args:
        errors: 上一轮生成或校验产生的错误信息。

    Returns:
        可直接附加到 LLM 请求中的反馈行；没有错误时返回空列表。
    """
    if not errors:
        return []
    lines: list[str] = []
    for error in errors:
        lines.append(f"- {error}")
        if "chart_config" in error:
            lines.append(
                '  Fix: ECharts placeholders (<div class="echarts-chart" data-chart-id="...">) and '
                'the config block (<template id="chart-configs">[...]</template> at the end) MUST appear '
                "in pairs with matching ids. Either remove ALL placeholder divs and render those charts as "
                "CSS bar rows instead, or add/fix the template block so every placeholder has one config "
                "entry with the same id."
            )
    lines.insert(
        0,
        "Your previous output failed validation. Fix ALL of the following issues and regenerate:",
    )
    if any("truncated" in error for error in errors):
        lines.append(
            "The previous output was truncated. Reduce CSS size and use fewer charts so the full output fits."
        )
    return lines


def _shell_messages(
    title: str,
    summary_md: str,
    sections: list[BriefHtmlSectionChunk],
    language: str,
    errors: list[str],
) -> dict:
    """构造 shell 生成请求上下文。

    Args:
        title: 报告标题。
        summary_md: 核心摘要 Markdown。
        sections: 章节列表，用于生成目录信息。
        language: 报告语言标识。
        errors: 需要反馈给 shell 生成模型的错误信息。

    Returns:
        供 shell Prompt 使用的请求上下文字典。
    """
    content_parts = [f"Report title: {title}"]
    if summary_md:
        content_parts.append(f"Executive Summary Markdown:\n{summary_md}")
    if sections:
        titles = "\n".join(f"- {chunk.section_id} {chunk.title}" for chunk in sections)
        content_parts.append(f"Section titles (in order, for the table of contents):\n{titles}")
    feedback = _error_feedback_lines(
        [error for error in errors if not error.startswith("section ")]
    )
    if feedback:
        content_parts.append("\n".join(feedback))
    return {
        "language": language,
        "messages": [{"role": "user", "content": "\n\n".join(content_parts)}],
    }


def _section_messages(
    chunk: BriefHtmlSectionChunk,
    shell_css: str,
    language: str,
    errors: list[str],
) -> dict:
    """构造章节片段生成请求上下文。

    Args:
        chunk: 当前章节及其 Markdown 内容。
        shell_css: shell 中可复用的 CSS 类定义。
        language: 报告语言标识。
        errors: 需要反馈给章节生成模型的错误信息。

    Returns:
        供章节 Prompt 使用的请求上下文字典。
    """
    content_parts = [f"Section Markdown:\n{chunk.markdown}"]
    if shell_css:
        content_parts.append(f"Shell CSS (class vocabulary you MUST reuse):\n{shell_css}")
    section_errors = [
        error
        for error in errors
        if not error.startswith("section ") or error.startswith(f"section {chunk.section_id}:")
    ]
    feedback = _error_feedback_lines(section_errors)
    if feedback:
        content_parts.append(
            f"You are generating section {chunk.section_id}.\n" + "\n".join(feedback)
        )
    return {
        "language": language,
        "messages": [{"role": "user", "content": "\n\n".join(content_parts)}],
    }


async def _generate_shell(
    llm,
    context: _ShellGenerationContext,
    *,
    attempt_num: int = 1,
) -> str | None:
    """生成报告 shell（设计系统、摘要、目录与挂载点）。

    Args:
        llm: 用于生成 shell 的 LLM 实例。
        context: shell 生成所需的报告上下文。
        attempt_num: 当前生成尝试序号，用于日志关联。

    Returns:
        清理后的 HTML shell；LLM 输出缺少完整报告结构时返回 ``None``。
    """
    started = time.perf_counter()
    logger.info(
        "[BriefHtmlReporter] event=shell_start attempt=%d.",
        attempt_num,
    )
    try:
        response = await ainvoke_llm_with_stats(
            llm,
            apply_system_prompt(
                "brief_html_reporter",
                _shell_messages(
                    context.title,
                    context.summary_md,
                    context.sections,
                    context.language,
                    context.errors,
                ),
            ),
            agent_name=AgentLlmName.BRIEF_HTML_REPORTER_SHELL.value,
        )
        raw = str(response.get("content") or "")
        html_body = _extract_html_body(raw)
        if html_body is None:
            logger.warning(
                "[BriefHtmlReporter] No <html_report> block found; raw_chars=%d head=%.200s tail=%.200s.",
                len(raw), raw[:200], raw[-200:],
            )
            logger.info(
                "[BriefHtmlReporter] event=shell_done attempt=%d status=failed reason=missing_html_report "
                "raw_chars=%d duration_ms=%.2f.",
                attempt_num,
                len(raw),
                (time.perf_counter() - started) * 1000,
            )
            return None
        sanitized = sanitize_html(html_body)
    except Exception as exc:
        logger.info(
            "[BriefHtmlReporter] event=shell_done attempt=%d status=failed error_type=%s duration_ms=%.2f.",
            attempt_num,
            type(exc).__name__,
            (time.perf_counter() - started) * 1000,
        )
        raise
    logger.info(
        "[BriefHtmlReporter] event=shell_done attempt=%d status=success raw_chars=%d chars=%d duration_ms=%.2f.",
        attempt_num,
        len(raw),
        len(sanitized),
        (time.perf_counter() - started) * 1000,
    )
    return sanitized


async def _generate_section_fragments(
    llm,
    shell: str,
    sections: list[BriefHtmlSectionChunk],
    language: str,
    errors: list[str],
    *,
    attempt_num: int = 1,
) -> tuple[dict[str, tuple[str, list[dict]]], list[str]]:
    """并行生成章节片段，返回成功缓存与失败章节错误。

    Args:
        llm: 用于生成章节片段的 LLM 实例。
        shell: 已生成并清理后的报告 shell。
        sections: 待生成的章节列表。
        language: 报告输出语言。
        errors: 上一轮生成错误，用于构造重试反馈。
        attempt_num: 当前生成尝试序号，用于日志关联。

    Returns:
        成功章节及其图表配置的映射，以及本轮失败章节的错误列表。
    """
    batch_started = time.perf_counter()
    logger.info(
        "[BriefHtmlReporter] event=section_batch_start attempt=%d count=%d.",
        attempt_num,
        len(sections),
    )
    shell_scanner = _HtmlStructureScanner()
    shell_scanner.feed(shell)
    shell_scanner.close()
    shell_css = "\n".join(shell_scanner.style_blocks)

    async def _one(chunk: BriefHtmlSectionChunk) -> tuple[str, list[dict]]:
        """生成并校验一个章节片段。

        Args:
            chunk: 当前待生成的章节块。

        Returns:
            章节 HTML 片段及其中可用的图表配置列表。

        Raises:
            ValueError: 章节片段缺失、为空或包含不允许的 CSS 外部引用。
        """
        started = time.perf_counter()
        logger.info(
            "[BriefHtmlReporter] event=section_start attempt=%d section_id=%s.",
            attempt_num,
            chunk.section_id,
        )
        try:
            response = await ainvoke_llm_with_stats(
                llm,
                apply_system_prompt(
                    "brief_html_section",
                    _section_messages(chunk, shell_css, language, errors),
                ),
                agent_name=AgentLlmName.BRIEF_HTML_REPORTER_SECTION.value,
            )
            raw = str(response.get("content") or "")
            fragment = _extract_section_fragment(raw)
            if fragment is None:
                raise ValueError(
                    f"section {chunk.section_id}: missing or unclosed <html_section> block "
                    "(output likely truncated)"
                )
            sanitized = _sanitize_fragment(fragment)
            if not sanitized.strip():
                raise ValueError(f"section {chunk.section_id}: empty fragment")
            fragment_scanner = _HtmlStructureScanner()
            fragment_scanner.feed(sanitized)
            fragment_scanner.close()
            css_errors = _validate_css_references(fragment_scanner)
            if css_errors:
                raise ValueError("; ".join(css_errors))
            fragment, configs = _extract_fragment_charts(sanitized, chunk.section_id)
            result = _ensure_section_anchor(fragment, chunk.section_id), configs
        except Exception as exc:
            logger.info(
                "[BriefHtmlReporter] event=section_done attempt=%d section_id=%s status=failed "
                "error_type=%s duration_ms=%.2f.",
                attempt_num,
                chunk.section_id,
                type(exc).__name__,
                (time.perf_counter() - started) * 1000,
            )
            raise
        logger.info(
            "[BriefHtmlReporter] event=section_done attempt=%d section_id=%s status=success "
            "raw_chars=%d sanitized_chars=%d fragment_chars=%d charts=%d duration_ms=%.2f.",
            attempt_num,
            chunk.section_id,
            len(raw),
            len(sanitized),
            len(result[0]),
            len(result[1]),
            (time.perf_counter() - started) * 1000,
        )
        return result

    # gather 保留每个章节的结果，便于缓存成功章节并只重试失败章节。
    results = await asyncio.gather(
        *(_one(chunk) for chunk in sections),
        return_exceptions=True,
    )
    generated: dict[str, tuple[str, list[dict]]] = {}
    section_errors: list[str] = []
    for chunk, result in zip(sections, results, strict=True):
        if isinstance(result, Exception):
            section_errors.append(f"section {chunk.section_id}: {result}")
            continue
        # CancelledError 等 BaseException 不应被当成普通章节失败吞掉。
        if isinstance(result, BaseException):
            raise result
        fragment, chunk_configs = result
        generated[chunk.section_id] = (fragment, chunk_configs)
    logger.info(
        "[BriefHtmlReporter] event=section_batch_done attempt=%d count=%d succeeded=%d failed=%d "
        "duration_ms=%.2f.",
        attempt_num,
        len(sections),
        len(generated),
        len(section_errors),
        (time.perf_counter() - batch_started) * 1000,
    )
    return generated, section_errors


class _BarFillTextNormalizer(HTMLParser):
    """移除 CSS 填充条内部内容，保留填充条本身及其属性。

    Attributes:
        out: 重新序列化后的 HTML 片段。
        normalized_count: 被移除文本的 ``bar-fill`` 元素数量。
    """

    def __init__(self) -> None:
        """初始化 bar-fill 内容清理状态。"""
        super().__init__(convert_charrefs=False)
        self.out: list[str] = []
        self._bar_fill_depth = 0
        self._bar_fill_had_content = False
        self.normalized_count = 0

    @staticmethod
    def _is_bar_fill(attrs: list) -> bool:
        """判断属性列表是否将元素标记为视觉填充条。

        Args:
            attrs: HTMLParser 提取的属性列表。

        Returns:
            元素 class 包含 ``bar-fill`` 时返回 ``True``。
        """
        return any(
            name
            and name.lower() == "class"
            and "bar-fill" in (value or "").split()
            for name, value in attrs
        )

    def handle_starttag(self, tag: str, attrs: list) -> None:
        """处理普通开始标签并进入必要的 bar-fill 丢弃状态。

        Args:
            tag: 开始标签名称。
            attrs: 开始标签属性列表。
        """
        lowered = tag.lower()
        if self._bar_fill_depth:
            # bar-fill 只保留外层元素，内部文本和嵌套元素均视为装饰内容。
            if lowered not in _HTML_VOID_TAGS:
                self._bar_fill_depth += 1
            self._bar_fill_had_content = True
            return
        self.out.append(self.get_starttag_text() or f"<{tag}>")
        if lowered not in _HTML_VOID_TAGS and self._is_bar_fill(attrs):
            self._bar_fill_depth = 1
            self._bar_fill_had_content = False

    def handle_startendtag(self, tag: str, attrs: list) -> None:
        """处理自闭合标签，并在 bar-fill 内部忽略其输出。

        Args:
            tag: 自闭合标签名称。
            attrs: 自闭合标签属性列表。
        """
        if not self._bar_fill_depth:
            self.out.append(self.get_starttag_text() or f"<{tag}/>")

    def handle_endtag(self, tag: str) -> None:
        """处理结束标签并维护 bar-fill 嵌套深度。

        Args:
            tag: 结束标签名称。
        """
        if self._bar_fill_depth:
            if tag.lower() not in _HTML_VOID_TAGS:
                self._bar_fill_depth -= 1
                if self._bar_fill_depth == 0:
                    if self._bar_fill_had_content:
                        self.normalized_count += 1
                    self._bar_fill_had_content = False
                    self.out.append(f"</{tag}>")
            return
        self.out.append(f"</{tag}>")

    def handle_data(self, data: str) -> None:
        """处理文本节点，只记录 bar-fill 是否包含可见内容。

        Args:
            data: HTMLParser 提取的文本内容。
        """
        if self._bar_fill_depth:
            self._bar_fill_had_content |= bool(data.strip())
        else:
            self.out.append(data)

    def handle_entityref(self, name: str) -> None:
        """处理命名字符实体。

        Args:
            name: HTML 字符实体名称。
        """
        if self._bar_fill_depth:
            self._bar_fill_had_content = True
        else:
            self.out.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        """处理数字字符实体。

        Args:
            name: HTML 字符实体数字表示。
        """
        if self._bar_fill_depth:
            self._bar_fill_had_content = True
        else:
            self.out.append(f"&#{name};")

    def handle_comment(self, data: str) -> None:
        """保留不在 bar-fill 内部的 HTML 注释。

        Args:
            data: 注释正文。
        """
        if not self._bar_fill_depth:
            self.out.append(f"<!--{data}-->")

    def handle_decl(self, decl: str) -> None:
        """保留不在 bar-fill 内部的 HTML 声明。

        Args:
            decl: 声明正文，例如 ``DOCTYPE html``。
        """
        if not self._bar_fill_depth:
            self.out.append(f"<!{decl}>")


def normalize_bar_fill_text(html_text: str) -> str:
    """将 bar-fill 规范化为纯视觉元素，避免薄条裁切文字。

    Args:
        html_text: 待处理的 HTML 文本。

    Returns:
        移除 bar-fill 内部内容后的 HTML 文本。
    """
    parser = _BarFillTextNormalizer()
    parser.feed(html_text)
    parser.close()
    normalized = "".join(parser.out)
    if parser.normalized_count:
        logger.warning(
            "[BriefHtmlReporter] Removed content from %d CSS bar fill(s); bar-fill is visual-only.",
            parser.normalized_count,
        )
    return normalized


def _assemble_html_report(
    shell: str,
    fragments: list[str],
    configs: list[dict],
    pre: BriefHtmlPreprocessResult,
    language: str,
) -> str:
    """拼装 shell、章节、引用和图表配置。

    Args:
        shell: 已清理的报告外壳及挂载点。
        fragments: 按章节顺序排列的 HTML 片段。
        configs: 章节提取出的 ECharts 配置。
        pre: Markdown 预处理结果及引用注册表。
        language: 报告语言标识。

    Returns:
        注入章节、引用和图表配置后的 HTML 文档。
    """
    fragments, configs = _normalize_chart_configs(fragments, configs)
    shell = _TEMPLATE_BLOCK_RE.sub("", shell)
    sections_html = "\n".join(fragments)
    if _MOUNT_SECTIONS_RE.search(shell):
        html_doc = _MOUNT_SECTIONS_RE.sub(lambda _match: sections_html, shell, count=1)
    else:
        logger.warning(
            "[BriefHtmlReporter] Shell missing #brief-sections mount; insert before </body>."
        )
        html_doc = _insert_before(shell, "</body>", f"{sections_html}\n")
    references_html = _render_references_html(pre, language)
    if _MOUNT_REFERENCES_RE.search(html_doc):
        html_doc = _MOUNT_REFERENCES_RE.sub(
            lambda _match: references_html, html_doc, count=1
        )
    elif references_html:
        html_doc = _insert_before(html_doc, "</body>", f"{references_html}\n")
    if configs:
        payload = html.escape(json.dumps(configs, ensure_ascii=True), quote=False)
        html_doc = _insert_before(
            html_doc,
            "</body>",
            f'\n<template id="chart-configs">{payload}</template>\n',
        )
    html_doc = normalize_bar_fill_text(html_doc)
    return convert_inline_citations(html_doc, pre)


async def generate_brief_html_report(*, llm, markdown: str, language: str) -> str:
    """把 Brief Markdown 转写为自包含 HTML，按 shell/章节粒度重试。

    Args:
        llm: 用于生成 shell 和章节片段的 LLM 实例。
        markdown: 溯源校验后的 Brief Markdown 报告。
        language: 报告输出语言。

    Returns:
        注入必要运行时并通过安全校验的自包含 HTML 报告。

    Raises:
        ValueError: 达到最大重试次数后仍无法生成有效 HTML。
    """
    started = time.perf_counter()
    logger.info(
        "[BriefHtmlReporter] event=html_start markdown_chars=%d language=%s.",
        len(markdown),
        language,
    )
    preprocess_started = time.perf_counter()
    pre = preprocess_markdown(markdown)
    title, summary_md, sections = _split_report_markdown(pre.cleaned_markdown)
    max_attempts = max(1, Config().service_config.report_max_generate_retry_num)
    logger.info(
        "[BriefHtmlReporter] event=preprocess_done cleaned_chars=%d sections=%d references=%d "
        "max_attempts=%d duration_ms=%.2f.",
        len(pre.cleaned_markdown),
        len(sections),
        len(pre.reference_entries),
        max_attempts,
        (time.perf_counter() - preprocess_started) * 1000,
    )
    errors: list[str] = []
    shell: str | None = None
    section_cache: dict[str, tuple[str, list[dict]]] = {}
    for attempt_num in range(max_attempts):
        # shell 校验失败时必须重新生成整体结构；仅章节失败时复用 shell 和已成功章节。
        reuse_shell = shell is not None and bool(errors) and all(
            error.startswith("section ") for error in errors
        )
        if not reuse_shell:
            section_cache.clear()
        # 成功章节跨轮缓存，避免一次局部失败导致所有章节重复调用 LLM。
        pending_sections = [
            chunk for chunk in sections if chunk.section_id not in section_cache
        ]
        logger.info(
            "[BriefHtmlReporter] event=attempt_start attempt=%d/%d sections=%d cached_sections=%d "
            "pending_sections=%d reuse_shell=%s errors=%d.",
            attempt_num + 1,
            max_attempts,
            len(sections),
            len(section_cache),
            len(pending_sections),
            reuse_shell,
            len(errors),
        )
        if not reuse_shell:
            shell = await _generate_shell(
                llm,
                _ShellGenerationContext(
                    title=title,
                    summary_md=summary_md,
                    sections=sections,
                    language=language,
                    errors=errors,
                ),
                attempt_num=attempt_num + 1,
            )
            if shell is None:
                errors = [
                    "shell: missing or unclosed <html_report> tag (output likely truncated)"
                ]
                logger.info(
                    "[BriefHtmlReporter] event=retry_scheduled attempt=%d/%d reason=shell_generation.",
                    attempt_num + 1,
                    max_attempts,
                )
                continue
        generated, section_errors = await _generate_section_fragments(
            llm,
            shell,
            pending_sections,
            language,
            errors,
            attempt_num=attempt_num + 1,
        )
        section_cache.update(generated)
        if section_errors:
            errors = section_errors
            logger.warning(
                "[BriefHtmlReporter] Section generation failed; attempt=%d/%d errors=%s.",
                attempt_num + 1, max_attempts, errors,
            )
            failed_section_ids = [
                chunk.section_id
                for chunk in pending_sections
                if chunk.section_id not in generated
            ]
            logger.info(
                "[BriefHtmlReporter] event=retry_scheduled attempt=%d/%d reason=section_generation "
                "failed_section_ids=%s cached_sections=%d.",
                attempt_num + 1,
                max_attempts,
                ",".join(failed_section_ids) or "-",
                len(section_cache),
            )
            continue
        fragments = [section_cache[chunk.section_id][0] for chunk in sections]
        configs = [
            config
            for chunk in sections
            for config in section_cache[chunk.section_id][1]
        ]
        assembly_started = time.perf_counter()
        assembled = _assemble_html_report(shell, fragments, configs, pre, language)
        logger.info(
            "[BriefHtmlReporter] event=assembly_done attempt=%d fragments=%d chart_configs=%d "
            "references=%d chars=%d duration_ms=%.2f.",
            attempt_num + 1,
            len(fragments),
            len(configs),
            len(pre.reference_entries),
            len(assembled),
            (time.perf_counter() - assembly_started) * 1000,
        )
        validation_started = time.perf_counter()
        errors, warnings = validate_html_report(assembled)
        logger.info(
            "[BriefHtmlReporter] event=validation_done attempt=%d status=%s errors=%d warnings=%d "
            "duration_ms=%.2f.",
            attempt_num + 1,
            "failed" if errors else "success",
            len(errors),
            len(warnings),
            (time.perf_counter() - validation_started) * 1000,
        )
        for warning in warnings:
            logger.warning("[BriefHtmlReporter] Generation warning: %s.", warning)
        if errors:
            logger.warning(
                "[BriefHtmlReporter] Validation failed; attempt=%d/%d errors=%s.",
                attempt_num + 1, max_attempts, errors,
            )
            logger.info(
                "[BriefHtmlReporter] event=retry_scheduled attempt=%d/%d reason=validation errors=%d.",
                attempt_num + 1,
                max_attempts,
                len(errors),
            )
            continue
        postprocess_started = time.perf_counter()
        result = inject_chart_scripts(assembled)
        result = inject_echarts_library(result)
        result = inject_ai_notice(result, language)
        final_security_assert(result)
        logger.info(
            "[BriefHtmlReporter] event=postprocess_done attempt=%d chart_configs=%d chars=%d "
            "duration_ms=%.2f.",
            attempt_num + 1,
            len(configs),
            len(result),
            (time.perf_counter() - postprocess_started) * 1000,
        )
        logger.info(
            "[BriefHtmlReporter] event=html_done status=success attempt=%d sections=%d "
            "references=%d chart_configs=%d chars=%d duration_ms=%.2f.",
            attempt_num + 1,
            len(sections),
            len(pre.reference_entries),
            len(configs),
            len(result),
            (time.perf_counter() - started) * 1000,
        )
        return result
    logger.info(
        "[BriefHtmlReporter] event=html_done status=failed attempts=%d errors=%d duration_ms=%.2f.",
        max_attempts,
        len(errors),
        (time.perf_counter() - started) * 1000,
    )
    raise ValueError(f"brief html report generation failed: {'; '.join(errors)}")
