"""Brief 报告的自包含 HTML 生成与并行编排。"""

import asyncio
import html
import json
import logging
import re
from dataclasses import dataclass
from html.parser import HTMLParser

from openjiuwen_deepsearch.algorithm.brief_report.html_charts import (
    _TEMPLATE_BLOCK_RE,
    _extract_fragment_charts,
    _normalize_chart_configs,
    _validate_chart_configs,
    inject_chart_scripts,
    inject_echarts_library,
)
from openjiuwen_deepsearch.algorithm.brief_report.html_content import (
    BriefHtmlPreprocessResult,
    BriefHtmlSectionChunk,
    _render_references_html,
    _split_report_markdown,
    convert_inline_citations,
    preprocess_markdown,
)
from openjiuwen_deepsearch.algorithm.brief_report.html_safety import (
    _HTML_VOID_TAGS,
    _HtmlStructureScanner,
    _JAVASCRIPT_URL_RE,
    _SCRIPT_TAG_RE,
    _contains_event_attribute,
    _insert_before,
    _validate_css_references,
    final_security_assert,
    sanitize_html,
)
from openjiuwen_deepsearch.algorithm.prompts.template import apply_system_prompt
from openjiuwen_deepsearch.common.common_constants import ENGLISH
from openjiuwen_deepsearch.config.config import Config
from openjiuwen_deepsearch.utils.common_utils.llm_utils import ainvoke_llm_with_stats
from openjiuwen_deepsearch.utils.constants_utils.node_constants import AgentLlmName


logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class _ShellGenerationContext:
    """shell 生成所需的报告上下文。"""

    title: str
    summary_md: str
    sections: list[BriefHtmlSectionChunk]
    language: str
    errors: list[str]


def validate_html_report(html_text: str) -> tuple[list[str], list[str]]:
    """对清理后的 HTML 聚合安全与图表结构校验。"""
    errors: list[str] = []
    warnings: list[str] = []
    lowered = html_text.lower()
    if "<!doctype html" not in lowered:
        errors.append("missing_doctype")
    for tag in ("html", "head", "body"):
        if f"<{tag}" not in lowered or f"</{tag}>" not in lowered:
            errors.append(f"missing_or_unclosed_{tag}")
    if _SCRIPT_TAG_RE.search(html_text):
        errors.append("script_tag_present")
    if _JAVASCRIPT_URL_RE.search(html_text):
        errors.append("javascript_url_present")

    scanner = _HtmlStructureScanner()
    scanner.feed(html_text)
    scanner.close()
    if _contains_event_attribute(html_text):
        errors.append("event_attribute_present")
    errors.extend(_validate_css_references(scanner))
    chart_errors, chart_warnings = _validate_chart_configs(scanner)
    errors.extend(chart_errors)
    warnings.extend(chart_warnings)
    return errors, warnings


def inject_ai_notice(html_text: str, language: str) -> str:
    """在 body 末尾确定性插入随语言切换的 AI 生成声明。"""
    text = (
        "This research report was generated by AI and is for reference only."
        if language == ENGLISH
        else "本研究报告由 AI 生成，仅供参考"
    )
    notice = (
        '<footer style="margin-top:48px;padding:26px 16px 10px;'
        'border-top:1px solid var(--border,#e8e6e0);text-align:center;">'
        '<p style="margin:0;font-size:12px;line-height:1.7;'
        'color:var(--text-muted,#8f8f8b);letter-spacing:.3px;">'
        '<span style="display:inline-block;padding:2px 10px;margin-right:8px;'
        'border-radius:999px;background:var(--accent-light,#f0efec);'
        'color:var(--accent,#6b6b68);font-weight:600;font-size:11px;'
        'line-height:1.5;">AI</span>'
        f"{text}</p></footer>"
    )
    return _insert_before(html_text, "</body>", f"{notice}\n")


_HTML_REPORT_BLOCK_RE = re.compile(r"(?s)<html_report>\s*(.*?)\s*</html_report>")
_HTML_SECTION_BLOCK_RE = re.compile(r"(?s)<html_section>\s*(.*?)\s*</html_section>")
_MOUNT_SECTIONS_RE = re.compile(r'(?is)<div id="brief-sections"[^>]*>\s*</div>')
_MOUNT_REFERENCES_RE = re.compile(r'(?is)<div id="brief-references"[^>]*>\s*</div>')


def _extract_html_body(raw: str) -> str | None:
    """从 LLM 输出提取完整 HTML，兼容缺少外层包装或 html 闭合标签。"""
    match = _HTML_REPORT_BLOCK_RE.search(raw)
    if match is not None:
        return match.group(1)
    lowered = raw.lower()
    start = lowered.find("<!doctype")
    if start < 0:
        return None
    end = lowered.rfind("</html>")
    if end >= 0:
        return raw[start:end + len("</html>")].strip()
    if "</body>" in lowered:
        return raw[start:].rstrip().removesuffix("</html_report>").rstrip() + "\n</html>"
    return None


def _extract_section_fragment(raw: str) -> str | None:
    """从 LLM 输出提取章节片段，兼容裸 h2 片段。"""
    match = _HTML_SECTION_BLOCK_RE.search(raw)
    if match is not None:
        return match.group(1)
    stripped = re.sub(r"(?m)^\s*```[a-zA-Z]*\s*$", "", raw).strip()
    if "<h2" in stripped.lower():
        return stripped
    return None


def _sanitize_fragment(fragment: str) -> str:
    """包成完整文档复用 sanitizer，再取回 body 内容。"""
    wrapped = f"<!DOCTYPE html><html><head></head><body>{fragment}</body></html>"
    cleaned = sanitize_html(wrapped)
    start = cleaned.find("<body>")
    end = cleaned.rfind("</body>")
    if start < 0 or end < 0:
        return ""
    return cleaned[start + len("<body>"):end]


def _error_feedback_lines(errors: list[str]) -> list[str]:
    """把上一轮错误格式化为可执行的 LLM 反馈。"""
    if not errors:
        return []
    lines: list[str] = []
    for error in errors:
        lines.append(f"- {error}")
        if "chart_config" in error:
            lines.append(
                '  Fix: ECharts placeholders (<div class="echarts-chart" data-chart-id="...">) and '
                'the config block (<template id="chart-configs">[...]</template> at the end) MUST appear '
                "in pairs with matching ids. Either remove ALL placeholder divs and render those charts as "
                "CSS bar rows instead, or add/fix the template block so every placeholder has one config "
                "entry with the same id."
            )
    lines.insert(
        0,
        "Your previous output failed validation. Fix ALL of the following issues and regenerate:",
    )
    if any("truncated" in error for error in errors):
        lines.append(
            "The previous output was truncated. Reduce CSS size and use fewer charts so the full output fits."
        )
    return lines


def _shell_messages(
    title: str,
    summary_md: str,
    sections: list[BriefHtmlSectionChunk],
    language: str,
    errors: list[str],
) -> dict:
    """构造 shell 生成请求上下文。"""
    content_parts = [f"Report title: {title}"]
    if summary_md:
        content_parts.append(f"Executive Summary Markdown:\n{summary_md}")
    if sections:
        titles = "\n".join(f"- {chunk.section_id} {chunk.title}" for chunk in sections)
        content_parts.append(f"Section titles (in order, for the table of contents):\n{titles}")
    feedback = _error_feedback_lines(
        [error for error in errors if not error.startswith("section ")]
    )
    if feedback:
        content_parts.append("\n".join(feedback))
    return {
        "language": language,
        "messages": [{"role": "user", "content": "\n\n".join(content_parts)}],
    }


def _section_messages(
    chunk: BriefHtmlSectionChunk,
    shell_css: str,
    language: str,
    errors: list[str],
) -> dict:
    """构造章节片段生成请求上下文。"""
    content_parts = [f"Section Markdown:\n{chunk.markdown}"]
    if shell_css:
        content_parts.append(f"Shell CSS (class vocabulary you MUST reuse):\n{shell_css}")
    section_errors = [
        error
        for error in errors
        if not error.startswith("section ") or error.startswith(f"section {chunk.section_id}:")
    ]
    feedback = _error_feedback_lines(section_errors)
    if feedback:
        content_parts.append(
            f"You are generating section {chunk.section_id}.\n" + "\n".join(feedback)
        )
    return {
        "language": language,
        "messages": [{"role": "user", "content": "\n\n".join(content_parts)}],
    }


async def _generate_shell(
    llm,
    context: _ShellGenerationContext,
) -> str | None:
    """生成报告 shell（设计系统、摘要、目录与挂载点）。"""
    response = await ainvoke_llm_with_stats(
        llm,
        apply_system_prompt(
            "brief_html_reporter",
            _shell_messages(
                context.title,
                context.summary_md,
                context.sections,
                context.language,
                context.errors,
            ),
        ),
        agent_name=AgentLlmName.BRIEF_HTML_REPORTER.value,
    )
    raw = str(response.get("content") or "")
    html_body = _extract_html_body(raw)
    if html_body is None:
        logger.warning(
            "[BriefHtmlReporter] No <html_report> block found; raw_chars=%d head=%.200s tail=%.200s.",
            len(raw), raw[:200], raw[-200:],
        )
        return None
    return sanitize_html(html_body)


async def _generate_section_fragments(
    llm,
    shell: str,
    sections: list[BriefHtmlSectionChunk],
    language: str,
    errors: list[str],
) -> tuple[dict[str, tuple[str, list[dict]]], list[str]]:
    """并行生成章节片段，返回成功缓存与失败章节错误。"""
    shell_scanner = _HtmlStructureScanner()
    shell_scanner.feed(shell)
    shell_scanner.close()
    shell_css = "\n".join(shell_scanner.style_blocks)

    async def _one(chunk: BriefHtmlSectionChunk) -> tuple[str, list[dict]]:
        response = await ainvoke_llm_with_stats(
            llm,
            apply_system_prompt(
                "brief_html_section",
                _section_messages(chunk, shell_css, language, errors),
            ),
            agent_name=AgentLlmName.BRIEF_HTML_REPORTER.value,
        )
        raw = str(response.get("content") or "")
        fragment = _extract_section_fragment(raw)
        if fragment is None:
            raise ValueError(
                f"section {chunk.section_id}: missing or unclosed <html_section> block "
                "(output likely truncated)"
            )
        sanitized = _sanitize_fragment(fragment)
        if not sanitized.strip():
            raise ValueError(f"section {chunk.section_id}: empty fragment")
        fragment_scanner = _HtmlStructureScanner()
        fragment_scanner.feed(sanitized)
        fragment_scanner.close()
        css_errors = _validate_css_references(fragment_scanner)
        if css_errors:
            raise ValueError("; ".join(css_errors))
        return _extract_fragment_charts(sanitized, chunk.section_id)

    if not sections:
        return {}, []
    results = await asyncio.gather(
        *(_one(chunk) for chunk in sections),
        return_exceptions=True,
    )
    generated: dict[str, tuple[str, list[dict]]] = {}
    section_errors: list[str] = []
    for chunk, result in zip(sections, results, strict=True):
        if isinstance(result, asyncio.CancelledError):
            raise result
        if isinstance(result, BaseException):
            section_errors.append(f"section {chunk.section_id}: {result}")
            continue
        fragment, chunk_configs = result
        generated[chunk.section_id] = (fragment, chunk_configs)
    return generated, section_errors


class _BarFillTextNormalizer(HTMLParser):
    """移除 CSS 填充条内部内容，保留填充条本身及其属性。"""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=False)
        self.out: list[str] = []
        self._bar_fill_depth = 0
        self._bar_fill_had_content = False
        self.normalized_count = 0

    @staticmethod
    def _is_bar_fill(attrs: list) -> bool:
        return any(
            name
            and name.lower() == "class"
            and "bar-fill" in (value or "").split()
            for name, value in attrs
        )

    def handle_starttag(self, tag: str, attrs: list) -> None:
        lowered = tag.lower()
        if self._bar_fill_depth:
            if lowered not in _HTML_VOID_TAGS:
                self._bar_fill_depth += 1
            self._bar_fill_had_content = True
            return
        self.out.append(self.get_starttag_text() or f"<{tag}>")
        if lowered not in _HTML_VOID_TAGS and self._is_bar_fill(attrs):
            self._bar_fill_depth = 1
            self._bar_fill_had_content = False

    def handle_startendtag(self, tag: str, attrs: list) -> None:
        if not self._bar_fill_depth:
            self.out.append(self.get_starttag_text() or f"<{tag}/>")

    def handle_endtag(self, tag: str) -> None:
        if self._bar_fill_depth:
            if tag.lower() not in _HTML_VOID_TAGS:
                self._bar_fill_depth -= 1
                if self._bar_fill_depth == 0:
                    if self._bar_fill_had_content:
                        self.normalized_count += 1
                    self._bar_fill_had_content = False
                    self.out.append(f"</{tag}>")
            return
        self.out.append(f"</{tag}>")

    def handle_data(self, data: str) -> None:
        if self._bar_fill_depth:
            self._bar_fill_had_content |= bool(data.strip())
        else:
            self.out.append(data)

    def handle_entityref(self, name: str) -> None:
        if self._bar_fill_depth:
            self._bar_fill_had_content = True
        else:
            self.out.append(f"&{name};")

    def handle_charref(self, name: str) -> None:
        if self._bar_fill_depth:
            self._bar_fill_had_content = True
        else:
            self.out.append(f"&#{name};")

    def handle_comment(self, data: str) -> None:
        if not self._bar_fill_depth:
            self.out.append(f"<!--{data}-->")

    def handle_decl(self, decl: str) -> None:
        if not self._bar_fill_depth:
            self.out.append(f"<!{decl}>")


def normalize_bar_fill_text(html_text: str) -> str:
    """将 bar-fill 规范化为纯视觉元素，避免薄条裁切文字。"""
    parser = _BarFillTextNormalizer()
    parser.feed(html_text)
    parser.close()
    normalized = "".join(parser.out)
    if parser.normalized_count:
        logger.warning(
            "[BriefHtmlReporter] Removed content from %d CSS bar fill(s); bar-fill is visual-only.",
            parser.normalized_count,
        )
    return normalized


def _assemble_html_report(
    shell: str,
    fragments: list[str],
    configs: list[dict],
    pre: BriefHtmlPreprocessResult,
    language: str,
) -> str:
    """拼装 shell、章节、引用和图表配置。"""
    fragments, configs = _normalize_chart_configs(fragments, configs)
    shell = _TEMPLATE_BLOCK_RE.sub("", shell)
    sections_html = "\n".join(fragments)
    if _MOUNT_SECTIONS_RE.search(shell):
        html_doc = _MOUNT_SECTIONS_RE.sub(lambda _match: sections_html, shell, count=1)
    else:
        logger.warning(
            "[BriefHtmlReporter] Shell missing #brief-sections mount; insert before </body>."
        )
        html_doc = _insert_before(shell, "</body>", f"{sections_html}\n")
    references_html = _render_references_html(pre, language)
    if _MOUNT_REFERENCES_RE.search(html_doc):
        html_doc = _MOUNT_REFERENCES_RE.sub(
            lambda _match: references_html, html_doc, count=1
        )
    elif references_html:
        html_doc = _insert_before(html_doc, "</body>", f"{references_html}\n")
    if configs:
        payload = html.escape(json.dumps(configs, ensure_ascii=True), quote=False)
        html_doc = _insert_before(
            html_doc,
            "</body>",
            f'\n<template id="chart-configs">{payload}</template>\n',
        )
    html_doc = normalize_bar_fill_text(html_doc)
    return convert_inline_citations(html_doc, pre)


async def generate_brief_html_report(*, llm, markdown: str, language: str) -> str:
    """把 Brief Markdown 转写为自包含 HTML，按 shell/章节粒度重试。"""
    pre = preprocess_markdown(markdown)
    title, summary_md, sections = _split_report_markdown(pre.cleaned_markdown)
    max_attempts = max(1, Config().service_config.report_max_generate_retry_num)
    errors: list[str] = []
    shell: str | None = None
    section_cache: dict[str, tuple[str, list[dict]]] = {}
    for attempt_num in range(max_attempts):
        logger.info(
            "[BriefHtmlReporter] Generate html report attempt=%d/%d sections=%d errors=%d.",
            attempt_num + 1, max_attempts, len(sections), len(errors),
        )
        reuse_shell = shell is not None and bool(errors) and all(
            error.startswith("section ") for error in errors
        )
        if not reuse_shell:
            section_cache.clear()
            shell = await _generate_shell(
                llm,
                _ShellGenerationContext(
                    title=title,
                    summary_md=summary_md,
                    sections=sections,
                    language=language,
                    errors=errors,
                ),
            )
            if shell is None:
                errors = [
                    "shell: missing or unclosed <html_report> tag (output likely truncated)"
                ]
                continue
        pending_sections = [
            chunk for chunk in sections if chunk.section_id not in section_cache
        ]
        generated, section_errors = await _generate_section_fragments(
            llm, shell, pending_sections, language, errors
        )
        section_cache.update(generated)
        if section_errors:
            errors = section_errors
            logger.warning(
                "[BriefHtmlReporter] Section generation failed; attempt=%d/%d errors=%s.",
                attempt_num + 1, max_attempts, errors,
            )
            continue
        fragments = [section_cache[chunk.section_id][0] for chunk in sections]
        configs = [
            config
            for chunk in sections
            for config in section_cache[chunk.section_id][1]
        ]
        assembled = _assemble_html_report(shell, fragments, configs, pre, language)
        errors, warnings = validate_html_report(assembled)
        for warning in warnings:
            logger.warning("[BriefHtmlReporter] Generation warning: %s.", warning)
        if errors:
            logger.warning(
                "[BriefHtmlReporter] Validation failed; attempt=%d/%d errors=%s.",
                attempt_num + 1, max_attempts, errors,
            )
            continue
        result = inject_chart_scripts(assembled)
        result = inject_echarts_library(result)
        result = inject_ai_notice(result, language)
        final_security_assert(result)
        logger.info("[BriefHtmlReporter] Generated html report chars=%d.", len(result))
        return result
    raise ValueError(f"brief html report generation failed: {'; '.join(errors)}")
